/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9jH5txouDmt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Caudex } from 'next/font/google'

caudex({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { eventForm } from "@/app/forms"
import { MultiselectField } from "@/components/multiselect-field"

export function EventForm() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <div className="flex-1 container mx-auto py-8 px-6">
        <form action={eventForm} className="bg-card p-6 rounded-md shadow-md mb-8">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-4">
              <div>
                <Label htmlFor="title">Title</Label>
                <Input id="title" placeholder="Enter news title" name="title" />
              </div>
              <div>
                <Label htmlFor="content">Content</Label>
                <Textarea id="content" rows={5} placeholder="Enter news content" name="description" />
              </div>
              <div>
                <Label htmlFor="date">Date</Label>
                <Input id="date" type="datetime-local" name="start_time" />
              </div>
              <div>
                <Label htmlFor="date">Date</Label>
                <Input id="date" type="datetime-lo  cal" name="end_time" />
              </div>
            <MultiselectField/>
              
            </div>
            <div>
              <Label htmlFor="image">Image</Label>
              <Input id="image" type="file"/>
            </div>
            
            

          </div>
          <div className="mt-6 flex justify-end">
            <Button type="submit">Publish</Button>
          </div>
        </form>
      </div>
    </div>
  )
}

function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>)
}
