/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9jH5txouDmt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Caudex } from 'next/font/google'

caudex({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"

export function event_form() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="bg-primary text-primary-foreground py-4 px-6">
        <div className="container mx-auto flex items-center justify-between">
          <h1 className="text-2xl font-bold">News</h1>
          <Link
            href="#"
            className="inline-flex items-center justify-center rounded-md bg-primary-foreground px-4 py-2 text-sm font-medium text-primary transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
            prefetch={false}
          >
            <PlusIcon className="mr-2 h-4 w-4" />
            New Post
          </Link>
        </div>
      </header>
      <div className="flex-1 container mx-auto py-8 px-6">
        <form className="bg-card p-6 rounded-md shadow-md mb-8">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-4">
              <div>
                <Label htmlFor="title">Title</Label>
                <Input id="title" placeholder="Enter news title" />
              </div>
              <div>
                <Label htmlFor="content">Content</Label>
                <Textarea id="content" rows={5} placeholder="Enter news content" />
              </div>
              <div>
                <Label htmlFor="date">Date</Label>
                <Input id="date" type="datetime-local" />
              </div>
              <div>
                <Label htmlFor="date">Date</Label>
                <Input id="date" type="datetime-local" />
              </div>
            </div>
            <div>
              <Label htmlFor="image">Image</Label>
              <Input id="image" type="file" />
            </div>
          </div>
          <div className="mt-6 flex justify-end">
            <Button type="submit">Publish</Button>
          </div>
        </form>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <Card>
            <img
              src="/placeholder.svg"
              alt="News Image"
              className="rounded-t-md object-cover w-full h-48"
              width="300"
              height="200"
              style={{ aspectRatio: "300/200", objectFit: "cover" }}
            />
            <CardContent>
              <h3 className="text-lg font-bold mb-2">Breaking News</h3>
              <p className="text-muted-foreground">
                This is a sample news article with an image. The content would go here.
              </p>
              <div className="mt-4 text-sm text-muted-foreground">April 15, 2023 at 10:30 AM</div>
            </CardContent>
          </Card>
          <Card>
            <img
              src="/placeholder.svg"
              alt="News Image"
              className="rounded-t-md object-cover w-full h-48"
              width="300"
              height="200"
              style={{ aspectRatio: "300/200", objectFit: "cover" }}
            />
            <CardContent>
              <h3 className="text-lg font-bold mb-2">Tech Update</h3>
              <p className="text-muted-foreground">
                This is another sample news article with an image. The content would go here.
              </p>
              <div className="mt-4 text-sm text-muted-foreground">May 1, 2023 at 2:45 PM</div>
            </CardContent>
          </Card>
          <Card>
            <img
              src="/placeholder.svg"
              alt="News Image"
              className="rounded-t-md object-cover w-full h-48"
              width="300"
              height="200"
              style={{ aspectRatio: "300/200", objectFit: "cover" }}
            />
            <CardContent>
              <h3 className="text-lg font-bold mb-2">Sports Highlights</h3>
              <p className="text-muted-foreground">
                This is a third sample news article with an image. The content would go here.
              </p>
              <div className="mt-4 text-sm text-muted-foreground">June 30, 2023 at 7:00 PM</div>
              <div className="mt-4 text-sm text-muted-foreground">June 30, 2023 at 7:00 PM</div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}

function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}
