/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/J5LHwzYOPMz
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Serif } from 'next/font/google'
import { Fraunces } from 'next/font/google'

ibm_plex_serif({
  subsets: ['latin'],
  display: 'swap',
})

fraunces({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function EventPage(data:[]) {
  return (
    <div>{data.length == 0 ? (<h1>Loading...</h1>) : (
    <div className="flex flex-col min-h-[100dvh] ">
      <main className="flex-1" >
        <section className="py-24 md:py-48 bg-cover bg-center" style={{ backgroundImage: 'url(/'+data['picture']+')' }}>
          <div className="">
            <div className="container mx-auto px-6 text-center text-popover">
              <h1 className="text-4xl font-bold tracking-wide  md:text-5xl">
                {data['title']}
              </h1>
              <p className="mt-4 text-lg">Москва, 13-я Парковая ул.</p>
            </div>
          </div>
        </section>
        <section className=" py-12 md:py-8">
          <div className="container mx-auto px-6">
            <div className="grid gap-12 md:grid-cols-2">
              <div>
              <h2 className="text-2xl text-center font-bold tracking-wide text-[#f87171]">О мероприятии</h2>
                <p className="text-foreground">
                  {data['description']}
                </p>
              </div>
              <div>
                <div className="bg-muted p-4 rounded-t-lg">
                  <strong className="text-foreground">Дата:</strong> {data['start_time'].slice(0,10)}
                </div>
                <div className="mt-8 bg-muted p-4 rounded-t-lg">
                  <strong className="text-foreground">Место проведения:</strong> Москва, 13-я Парковая ул.
                </div>
                <div className="mt-8 bg-muted p-4 rounded-t-lg">
                  <strong className="text-foreground">Билеты:</strong> Доступны к покупке как онлайн, так и на месте проведения мероприятия
                </div>
                <div className="mt-8 bg-muted p-4 rounded-t-lg">
                  <strong className="text-  ">Парковочные места:</strong> Ограниченная парковка на территории,рекомендуется общественный транспорт
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-16">
          <div className="container mx-auto px-6">
            <h2 className="text-2xl text-center font-bold tracking-wide text-foreground">Расписание</h2>
            <div className="mt-8 grid gap-6 md:grid-cols-2 lg:grid-cols-3">
              <div className="rounded-md border bg-card p-4 shadow">
              <h3 className="text-lg font-bold text-foreground">Пятница, Сентябрь 15</h3>
                <ul className="mt-4 space-y-4 text-muted-foreground">
                  <li>
                    <h4 className="font-medium text-foreground">Церемония открытия выставки «Устойчивая жизнь»</h4>
                    <p>9:00 - 10:00</p>
                  </li>
                  <li>
                    <h4 className="font-medium text-foreground">Основной доклад: Будущее экологически чистых городов</h4>
                    <p>10:30 - 12:00</p>
                  </li>
                  <li>
                    <h4 className="font-medium text-foreground">Мастер-класс</h4>
                    <p>13:00 PM - 15:00 </p>
                  </li>
                </ul>
              </div>
              <div className="rounded-md border bg-card p-4 shadow">
                <h3 className="text-lg font-bold text-foreground">Суббота, Сентябрь 16</h3>
                <ul className="mt-4 space-y-4 text-muted-foreground">
                  <li>
                    <h4 className="font-medium text-foreground">Панельная дискуссия: Устойчивая мода</h4>
                    <p>9:00 - 10:30</p>
                  </li>
                  <li>
                    <h4 className="font-medium text-foreground">Практический семинар: строительство собственного сада</h4>
                    <p>11:00 - 13:00</p>
                  </li>
                  <li>
                    <h4 className="font-medium text-foreground">Демонстрация экологически безопасного приготовления пищи</h4>
                    <p>14:30 PM - 16:00 PM</p>
                  </li>
                </ul>
              </div>
              <div className="rounded-md border bg-card p-4 shadow">
                <h3 className="text-lg font-bold text-foreground">Воскресенье, Сентябрь 17</h3>
                <ul className="mt-4 space-y-4 text-muted-foreground">
                  <li>
                    <h4 className="font-medium text-foreground">Мастер-класс по улучшению экологически чистого дома</h4>
                    <p>9:00 - 11:00</p>
                  </li>
                  <li>
                    <h4 className="font-medium text-foreground">Вопросы и ответы об устойчивом садоводстве</h4>
                    <p>12:00 - 13:30</p>
                  </li>
                  <li>
                    <h4 className="font-medium text-foreground">Церемония закрытия выставки</h4>
                    <p>13:30 - 17:00</p>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
    )} </div>
  )
}

function LeafIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z" />
      <path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}
