/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/6jX5NEcskbC
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

'use client'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { EventCard } from '@/components/event-card'
import { useState } from 'react';
import { useEffect } from 'react';
import { getEvents } from '@/app/Filters'
import {Logo} from '@/components/logo'
import { Space } from 'lucide-react';

export function Header(){
  return (
    <div className="bg-[#f5f5f5] py-6 px-4 md:px-8">
        <div className="flex items-center ml-32 justify-between">
          <Link href="/" className="flex items-center gap-2" prefetch={false}>
            <Logo className="h-8 w-8 text-green-500" />
            <span className="text-4xl font-semibold">ЭкоПросвет</span>
          </Link>
          {/* <nav className="flex items-center gap-6 mr-32">
            <Link href="#" className="text-gray-600 hover:text-green-500" prefetch={false}>
              Home
            </Link>
            <Link href="#" className="text-gray-600 hover:text-green-500" prefetch={false}>
              News
            </Link>
            <Link href="#" className="text-gray-600 hover:text-green-500" prefetch={false}>
              Features
            </Link>
            <Link href="#" className="text-gray-600 hover:text-green-500" prefetch={false}>
              About
            </Link>
            <Link href="#" className="text-gray-600 hover:text-green-500" prefetch={false}>
              Contact
            </Link>
          </nav> */}
          <Button variant="outline" className="">
            <Link href="/account/register">Регистрация</Link>
          </Button>
        </div>
    </div>
  )
}

export function Footer(){
  return (
    <div className="mx-auto flex items-center justify-between">
      <p className="text-sm text-gray-600 ml-32">&copy; 2024 Eco Event. All rights reserved.</p>
      <nav className="flex space-x-4 mr-32">
        <Link href="#" className="text-sm font-medium text-gray-600 hover:underline" prefetch={false}>
          Privacy Policy
        </Link>
        <Link href="#" className="text-sm font-medium text-gray-600 hover:underline" prefetch={false}>
          Terms of Service
        </Link>
      </nav>
    </div>
  )
}

export function NewsMain() {
  let filters = [useState(false),useState(false),useState(false),useState(false),useState(false),useState(false),useState(false),useState(false)]
  const [content, setContent] = useState([])
  const [search, setSearch] = useState('')
  function FilterButton(title:string, state:any){
    const [clicked, setClicked] = state

    function HandleClick(){
      setClicked(!clicked)
    }
    if (!clicked) {
      return (
        <div onClick={HandleClick} className="flex transition ease-in items-center gap-2 text-gray-600 text-xl hover:text-green-600 cursor-pointer">
          <LeafIcon className="transition ease-in h-6 w-6 text-green-500" />
          {title}
        </div>)
    } else {
      return (
        <div onClick={HandleClick} className="flex transition ease-in-out items-center gap-2 text-green-400 text-xl cursor-pointer">
          <LeafIcon className="transition ease-in h-6 w-6 text-green-400" />
          {title}
        </div>)
    }
  }
  async function applyFilter(){
    setContent(await getEvents(filters))
  }
  useEffect(() => {
    getEvents().then(result =>{
      setContent(result)
    })
  }, [search]);
  useEffect(() => {  

  }, [content])
  console.log(content)  
  return (
      <main className="flex-1">
        <section className="bg-[#f5f5f5] py-12 md:py-20">
          <div className="container mx-auto grid md:grid-cols-2 gap-8 items-center">
            <img
              src="/big.jpg"
              height={400}
              alt="Hero Image"
              className="rounded-lg object-cover w-full"
              style={{ aspectRatio: "600/400", objectFit: "cover" }}
            />
            <div className="space-y-4">
              <div className="inline-block bg-green-500 text-white px-3 py-1 rounded-full text-sm font-medium">
                Последние новости
              </div>
              <h1 className="text-3xl md:text-4xl font-bold tracking-tight">
              Всероссийский урок «Экология и энергосбережение»
              </h1>
              <p className="text-gray-600 text-lg">
              Цель: Способствовать воспитанию экологического сознания у детей; получению  детьми объективной, соответствующей их возрасту  информации об энергии и энергетических процессах, об источниках энергии и их роли в жизни человека, о правилах эффективного и экономного использования энергоресурсов.
              </p>
              <Link
                href="/event"
                className="inline-flex items-center gap-2 bg-green-500 text-white px-4 py-2 rounded-md hover:bg-green-600 transition-colors"
                prefetch={false}
              >
                Подробнее
                <ArrowRightIcon className="h-5 w-5" />
              </Link>
            </div>
          </div>
        </section>
        <section className="my-16">
          <div className="grid grid-cols-4 w-11/12 m-auto">
              <div className="bg-[#f5f5f5] w-80">
                <div className="p-6">
                  <h2 className="text-2xl font-bold mb-4">Категории</h2>
                  <nav className="space-y-3 text-lg">
                    {FilterButton('Лекция', filters[0])}
                    {FilterButton('Ярмарка', filters[1])}
                    {FilterButton('Квест', filters[2])}
                    {FilterButton('Волонтерство', filters[3])}
                  </nav>
                  <nav className="space-y-3 text-lg py-6">
                    {FilterButton('Дети', filters[4])}
                    {FilterButton('Молодежь', filters[5])}
                    {FilterButton('Зрелые', filters[6])}
                    {FilterButton('Пенсионеры', filters[7])}
                  </nav>
                  <Button onClick={applyFilter} className="mt-3 bg-green-500 text-white hover:bg-green-600 transition-colors w-64 text-lg">Filter</Button>
                  <div className='h-40 w-40'></div>
                </div>
              </div>
              <div className="col-span-3 grid gap-16 grid-cols-3">
                { content.length !== 0 ?  (content.map((el) => (
                  <div>{EventCard(el['id'], el['title'], el['description'], el['categories'].split(','), el['picture'])}</div>
                ))): (<div className='text-xl text-muted-foreground'>loading...</div>)} 
                {/* {EventCard(
                  'Crazy title',
                   'A local initiative is making waves by finding new ways to recycle materials, reducing landfill waste and promoting a circular economy. Also thas a bit sus',
                    ['Eco', 'Green'])} */}
                
              </div>
          </div>
        </section>
      </main>
  )
}

function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}


function CloudIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z" />
    </svg>
  )
}


function LeafIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z" />
      <path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function RecycleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 19H4.815a1.83 1.83 0 0 1-1.57-.881 1.785 1.785 0 0 1-.004-1.784L7.196 9.5" />
      <path d="M11 19h8.203a1.83 1.83 0 0 0 1.556-.89 1.784 1.784 0 0 0 0-1.775l-1.226-2.12" />
      <path d="m14 16-3 3 3 3" />
      <path d="M8.293 13.596 7.196 9.5 3.1 10.598" />
      <path d="m9.344 5.811 1.093-1.892A1.83 1.83 0 0 1 11.985 3a1.784 1.784 0 0 1 1.546.888l3.943 6.843" />
      <path d="m13.378 9.633 4.096 1.098 1.097-4.096" />
    </svg>
  )
}


function SunIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2" />
      <path d="M12 20v2" />
      <path d="m4.93 4.93 1.41 1.41" />
      <path d="m17.66 17.66 1.41 1.41" />
      <path d="M2 12h2" />
      <path d="M20 12h2" />
      <path d="m6.34 17.66-1.41 1.41" />
      <path d="m19.07 4.93-1.41 1.41" />
    </svg>
  )
}
