# Generated by Django 5.1.1 on 2024-09-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.CharField(default='template.png', max_length=200),
        ),
    ]
